/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: victory_mirosya (https://sketchfab.com/victory_mirosya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fox-f372c04de44640fbb6a4f9e4e5845c78
Title: Fox
*/

import { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { getDRACOLoader } from '../utils/dracoLoader'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import scene from '../assets/3d/fox.glb'

const Fox = ({currentAnimation, ...props}) => {
  const group = useRef()
  // Use DracoLoader for compressed GLB
  const { nodes, materials, animations } = useGLTF(scene, true, loader => {
    loader.setDRACOLoader(getDRACOLoader())
  })
  const { actions } = useAnimations(animations, group)

  // State for interactive features
  const [isHovered, setIsHovered] = useState(false)

  // Use refs instead of state for per-frame animation values to avoid 60fps re-renders
  const bodyRef = useRef()
  const tailRef = useRef()
  const headBoneRef = useRef()

  // Smoothed head-look offsets, layered on top of the baked animation
  const currentYaw = useRef(0)
  const currentPitch = useRef(0)
  const worldOffsetEuler = useRef(new THREE.Euler())
  const worldOffsetQuat = useRef(new THREE.Quaternion())
  const parentWorldQuat = useRef(new THREE.Quaternion())
  const invParentWorldQuat = useRef(new THREE.Quaternion())
  const localOffsetQuat = useRef(new THREE.Quaternion())
  const headBaseQuat = useRef(null)

  // Locate the head bone once the skeleton is available. "Bone004_2" was
  // identified by dumping bone world positions at rest pose - it's the
  // terminal bone of the spine->neck->head chain (tallest, furthest-forward
  // point in the skeleton, matching where a standing fox's head sits).
  // Its base local quaternion is captured once - the idle/walk clips don't
  // keyframe this particular bone, so the mixer never resets it between
  // frames. Without a fixed base to re-apply the offset to every frame, the
  // previous premultiply-in-place approach kept stacking the same small
  // rotation onto itself frame after frame, spinning the head continuously.
  useEffect(() => {
    if (group.current) {
      const bone = group.current.getObjectByName('Bone004_2')
      headBoneRef.current = bone
      headBaseQuat.current = bone ? bone.quaternion.clone() : null
    }
  }, [nodes])

  // Animation loop for continuous effects - mutate refs directly, no setState
  useFrame((state) => {
    const elapsed = state.clock.elapsedTime;

    // Breathing effect - directly mutate scale
    if (bodyRef.current) {
      const breathScale = 1 + Math.sin(elapsed * 1.5) * 0.01;
      bodyRef.current.scale.set(breathScale, breathScale, breathScale);
    }

    // Tail wagging - directly mutate rotation
    if (tailRef.current) {
      tailRef.current.rotation.z = Math.sin(elapsed * 2) * 0.2;
    }
  })

  // Head-look: nudge the head bone toward the cursor, layered on top of the
  // baked animation. No priority argument here - useFrame's priority isn't
  // just an ordering hint, a non-zero value disables r3f's automatic render
  // loop and makes the caller responsible for calling gl.render() itself.
  // Natural hook-registration order already runs this after useAnimations'
  // internal mixer update, since that hook is called earlier in this
  // component than this useFrame.
  //
  // This bone is animated via quaternion tracks, and Three.js never syncs
  // .rotation (Euler) from .quaternion changes made elsewhere - only the
  // reverse. Touching .rotation here would read/write a stale Euler and
  // clobber the mixer's real quaternion, corrupting the shared skeleton
  // (silently - it's numerically valid, just kinematically wrong, so every
  // skinned mesh sharing this skeleton goes invisible with no console error).
  // Staying in quaternion-space and multiplying an offset on top avoids that.
  //
  // This bone's LOCAL axes don't correspond to intuitive world yaw/pitch -
  // its neck/spine parent chain accumulates rotation, so e.g. rotating
  // purely around local Y visibly tilts the head "up" rather than turning
  // it left/right (confirmed by isolating each local axis in testing).
  // Instead of guessing a local axis, the desired look offset is expressed
  // as a WORLD-space rotation (yaw around world-up, pitch around world-right)
  // and conjugated into whatever local space this bone happens to have via
  // its parent's current world orientation: local = parentInverse * world *
  // parent. The parent's world matrix is refreshed first since matrixWorld
  // is otherwise only recomputed during the renderer's own pass, which runs
  // after this callback.
  useFrame((state) => {
    const head = headBoneRef.current
    const base = headBaseQuat.current
    if (!head || !head.parent || !base) return

    const maxYaw = THREE.MathUtils.degToRad(28)
    const maxPitch = THREE.MathUtils.degToRad(18)

    const targetYaw = THREE.MathUtils.clamp(state.pointer.x, -1, 1) * maxYaw
    const targetPitch = THREE.MathUtils.clamp(-state.pointer.y, -1, 1) * maxPitch

    currentYaw.current = THREE.MathUtils.lerp(currentYaw.current, targetYaw, 0.08)
    currentPitch.current = THREE.MathUtils.lerp(currentPitch.current, targetPitch, 0.08)

    worldOffsetEuler.current.set(currentPitch.current, currentYaw.current, 0)
    worldOffsetQuat.current.setFromEuler(worldOffsetEuler.current)

    head.parent.updateWorldMatrix(true, false)
    head.parent.getWorldQuaternion(parentWorldQuat.current)
    invParentWorldQuat.current.copy(parentWorldQuat.current).invert()

    localOffsetQuat.current
      .copy(invParentWorldQuat.current)
      .multiply(worldOffsetQuat.current)
      .multiply(parentWorldQuat.current)

    // Reset to the fixed base every frame, then apply the offset - never
    // premultiply in place on top of whatever's already there, since that's
    // what caused the runaway spin.
    head.quaternion.copy(base).premultiply(localOffsetQuat.current)
  })

  // Handle animation changes
  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach(action => action.stop());

      if(currentAnimation) {
        const action = actions[currentAnimation];
        if (action) {
          action.play();
        }
      }
    }
  }, [actions, currentAnimation])

  // Check if the model loaded properly
  if (!nodes || !materials) {
    return null;
  }

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onPointerOver={() => setIsHovered(true)}
      onPointerOut={() => setIsHovered(false)}
    >
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />

        {/* Main body with breathing effect */}
        <skinnedMesh
          ref={bodyRef}
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_7.skeleton}
        />

        {/* Head */}
        <skinnedMesh
          name="Object_8"
          geometry={nodes.Object_8.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_8.skeleton}
        />

        {/* Eyes */}
        <skinnedMesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_9.skeleton}
        />

        {/* Ears */}
        <skinnedMesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_10.skeleton}
        />

        {/* Tail with wagging effect */}
        <skinnedMesh
          ref={tailRef}
          name="Object_11"
          geometry={nodes.Object_11.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_11.skeleton}
        />
      </group>

      {/* Hover effect glow */}
      {isHovered && (
        <mesh position={[0, 0.5, 0]}>
          <sphereGeometry args={[1.2, 16, 16]} />
          <meshBasicMaterial
            color="#ff6b35"
            transparent
            opacity={0.1}
            side={THREE.BackSide}
          />
        </mesh>
      )}
    </group>
  )
}

export default Fox;
