/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import { useRef, useEffect, useCallback, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'
import { getDRACOLoader } from '../utils/dracoLoader'

import islandScene from '../assets/3d/island.glb'

const Island = ({
  isRotating, 
  setIsRotating, 
  currentStage,
  setCurrentStage, 
  planeDirection, 
  setPlaneDirection, 
  islandRotation: _islandRotation,
  setIslandRotation,
  ...props
}) => {

    const { gl, viewport } = useThree();
    const lastX = useRef(0);
    const rotatingSpeed = useRef(0);
    const dampingFactor = 0.92; // Reduced for smoother deceleration
    const targetPlaneDirection = useRef(Math.PI / 2); // Default facing left
    const isDirectionLocked = useRef(false); // Prevent direction changes when not rotating
    
    // Use DracoLoader for compressed GLB
    const { nodes, materials } = useGLTF(islandScene, true, loader => {
      loader.setDRACOLoader(getDRACOLoader())
    })
    const islandRef = useRef();

  const handlePointerDown = useCallback((e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);
    isDirectionLocked.current = false; // Allow direction changes when starting to rotate

    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    lastX.current = clientX;
  }, [setIsRotating]);
  
  const handlePointerUp = useCallback((e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
    isDirectionLocked.current = true; // Lock direction when stopping rotation
  }, [setIsRotating]);
  
  const handlePointerMove = useCallback((e) => {
    e.stopPropagation();
    e.preventDefault();

    if(isRotating) {
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;
      const delta = (clientX - lastX.current)/ viewport.width;
      
      // Determine desired rotation direction based on mouse movement
      const desiredRotation = delta * 0.03 * Math.PI; // Higher sensitivity for smoother rotation
      
      // Set plane direction based on rotation direction
      if (desiredRotation > 0) {
        // Rotating clockwise - plane should face right
        targetPlaneDirection.current = -Math.PI / 2; // -90 degrees (right)
      } else {
        // Rotating counter-clockwise - plane should face left
        targetPlaneDirection.current = Math.PI / 2; // 90 degrees (left)
      }
      
      // Allow island rotation immediately
      islandRef.current.rotation.y += desiredRotation;
      rotatingSpeed.current = desiredRotation;
      
      // Update state for smooth rotation
      setIslandRotation(islandRef.current.rotation.y);
      
      lastX.current = clientX;
    }
  }, [isRotating, viewport.width, setIslandRotation]);

  const handleKeyDown = useCallback((e) => {
    if(e.key === 'ArrowLeft') {
      if(!isRotating) setIsRotating(true);
      isDirectionLocked.current = false; // Allow direction changes
      
      // Rotate plane to face left and rotate island clockwise
      targetPlaneDirection.current = Math.PI / 2; // 90 degrees (left)
      islandRef.current.rotation.y += 0.03 * Math.PI; // Higher speed
      rotatingSpeed.current = 0.035;
      setIslandRotation(islandRef.current.rotation.y);
    } else if(e.key === 'ArrowRight') {
      if(!isRotating) setIsRotating(true);
      isDirectionLocked.current = false; // Allow direction changes
      
      // Rotate plane to face right and rotate island counter-clockwise
      targetPlaneDirection.current = -Math.PI / 2; // -90 degrees (right)
      islandRef.current.rotation.y -= 0.03 * Math.PI; // Higher speed
      rotatingSpeed.current = -0.035;
      setIslandRotation(islandRef.current.rotation.y);
    }
  }, [isRotating, setIsRotating, setIslandRotation]);

  const handleKeyUp = useCallback((e) => {
    if(e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
      setIsRotating(false);
      isDirectionLocked.current = true; // Lock direction when stopping rotation
    }
  }, [setIsRotating]);

  useFrame(() => {
    if (!islandRef.current) return;
    
    // Smoothly rotate plane to target direction (only left or right)
    if (!isDirectionLocked.current) {
      const currentAngle = planeDirection % (2 * Math.PI);
      const targetAngle = targetPlaneDirection.current;
      const angleDiff = targetAngle - currentAngle;
      
      // Normalize angle difference
      const normalizedDiff = Math.atan2(Math.sin(angleDiff), Math.cos(angleDiff));
      
      if (Math.abs(normalizedDiff) > 0.005) {
        setPlaneDirection(planeDirection + normalizedDiff * 0.25); // Much faster rotation
      } else if (Math.abs(normalizedDiff) > 0.0005) {
        // Set exact target when very close
        setPlaneDirection(targetAngle);
      }
    }
    
    // Only update rotation and stage when needed
    if(!isRotating) {
      if (Math.abs(rotatingSpeed.current) > 0.001) {
        rotatingSpeed.current *= dampingFactor;
        islandRef.current.rotation.y += rotatingSpeed.current;
        setIslandRotation(islandRef.current.rotation.y);
      }
    } else {
      // Only calculate stage when rotating and when rotation changes significantly
      const rotation = islandRef.current.rotation.y;
      const normalizedRotation = ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Memoize stage calculation to avoid unnecessary updates
      let newStage = null;
      if (normalizedRotation >= 5.45 && normalizedRotation <= 5.85) {
        newStage = 4;
      } else if (normalizedRotation >= 0.85 && normalizedRotation <= 1.3) {
        newStage = 3;
      } else if (normalizedRotation >= 2.4 && normalizedRotation <= 2.6) {
        newStage = 2;
      } else if (normalizedRotation >= 4.25 && normalizedRotation <= 4.75) {
        newStage = 1;
      }

      // Only update stage if it changed
      if (newStage !== currentStage) {
        setCurrentStage(newStage);
      }
    }
  })

  useEffect(() => {
    const canvas = gl.domElement;
    canvas.addEventListener('pointerup', handlePointerUp)
    canvas.addEventListener('pointerdown', handlePointerDown)
    canvas.addEventListener('pointermove', handlePointerMove)
    document.addEventListener('keydown', handleKeyDown)
    document.addEventListener('keyup', handleKeyUp)
    return () => {
      canvas.removeEventListener('pointerup', handlePointerUp)
      canvas.removeEventListener('pointerdown', handlePointerDown)
      canvas.removeEventListener('pointermove', handlePointerMove)
      document.removeEventListener('keydown', handleKeyDown)
      document.removeEventListener('keyup', handleKeyUp)
    }
  }, [gl, handlePointerDown, handlePointerUp, handlePointerMove, handleKeyDown, handleKeyUp]);

  // Memoize mesh components to prevent unnecessary re-renders
  // Must be before any early return to satisfy Rules of Hooks
  const meshComponents = useMemo(() => {
    if (!nodes || !materials) return null;
    return [
      <mesh key="tree1" geometry={nodes.polySurface944_tree_body_0.geometry} material={materials.PaletteMaterial001} />,
      <mesh key="tree2" geometry={nodes.polySurface945_tree1_0.geometry} material={materials.PaletteMaterial001} />,
      <mesh key="tree3" geometry={nodes.polySurface946_tree2_0.geometry} material={materials.PaletteMaterial001} />,
      <mesh key="tree4" geometry={nodes.polySurface947_tree1_0.geometry} material={materials.PaletteMaterial001} />,
      <mesh key="tree5" geometry={nodes.polySurface948_tree_body_0.geometry} material={materials.PaletteMaterial001} />,
      <mesh key="tree6" geometry={nodes.polySurface949_tree_body_0.geometry} material={materials.PaletteMaterial001} />,
      <mesh key="rocks" geometry={nodes.pCube11_rocks1_0.geometry} material={materials.PaletteMaterial001} />
    ];
  }, [nodes, materials]);

  if (!meshComponents) return null;

  return (
    <a.group
      ref={islandRef}
      {...props}
    >
      {meshComponents}
    </a.group>
  )
}

useGLTF.preload(islandScene)

export default Island;